### ISSUE TITLE
Livebox on non default IP address

### ISSUE THREAD

**Issue by simulot** [Cyr-ius/hass-livebox-component#1] opened 2020-01-04 22:45 UTC
Hi,
My livebox address is 192.168.10.1. I have setup this address in configuration.yaml as following:

``` yaml
livebox:
  host: 192.168.10.1
  username: 'admin'
  password: !secret livebox_password
```
The livebox entities doesn't show up. The debug level log shows some references to `http://192.168.1.1:80` despite settings.

The log:
``` log
2020-01-04 23:37:52 INFO (MainThread) [homeassistant.setup] Setting up livebox
2020-01-04 23:37:52 INFO (MainThread) [homeassistant.setup] Setup of domain livebox took 0.0 seconds.
2020-01-04 23:37:52 DEBUG (MainThread) [aiosysbus.access] http://192.168.1.1:80
2020-01-04 23:38:02 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Orange Livebox for livebox
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 184, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 164, in _new_conn
    % (self.host, self.timeout),
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0xb2566050>, 'Connection to 192.168.1.1 timed out. (connect timeout=10)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.1.1', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xb2566050>, 'Connection to 192.168.1.1 timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiosysbus/access.py", line 30, in _get_challenge
    r = self.session.get(url, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='192.168.1.1', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xb2566050>, 'Connection to 192.168.1.1 timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 192, in async_setup
    hass, self
  File "/config/custom_components/livebox/__init__.py", line 61, in async_setup_entry
    perms = await session.async_get_permissions()
  File "/usr/local/lib/python3.7/site-packages/aiosysbus/aiosysbus.py", line 59, in async_get_permissions
    return await self._access.get_permissions()
  File "/usr/local/lib/python3.7/site-packages/aiosysbus/access.py", line 146, in get_permissions
    await self._refresh_session_token()
  File "/usr/local/lib/python3.7/site-packages/aiosysbus/access.py", line 69, in _refresh_session_token
    session_token, session_permissions = await self._get_session_token()
  File "/usr/local/lib/python3.7/site-packages/aiosysbus/access.py", line 42, in _get_session_token
    challenge = await self._get_challenge(self.base_url, self.timeout)
  File "/usr/local/lib/python3.7/site-packages/aiosysbus/access.py", line 33, in _get_challenge
    .format(str(e)))
aiosysbus.exceptions.NotOpenError: Open session failed (APIResponse: HTTPConnectionPool(host='192.168.1.1', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xb2566050>, 'Connection to 192.168.1.1 timed out. (connect timeout=10)')))
```

I'm using a different network than default to avoid conflicts with entreprise VPN...
I have flashed lot of tasmota devices already. So changing my network to 192.168.1.1 is not my preferred option.

++ JFC

**Comment by Cyr-ius** [comment] 2020-01-05 10:52
I just fixed in 1.3.6, you can now change the ip and port of your livebox
Please report the correction to me in order to close the issue

**Comment by simulot** [comment] 2020-01-05 16:41
Good, the main sensor is working now. 
![image](https://user-images.githubusercontent.com/5980377/71783109-4e3daa80-2fe2-11ea-8726-869d088cf568.png)

As you can see, connection speed sensor are not working, as stated in #2

**Comment by Cyr-ius** [comment] 2020-01-11 12:48
Duplicate of #2

**Comment by Cyr-ius** [comment] 2020-01-11 12:48
Please look issue #2 for reponse.

**Closed by Cyr-ius** 2020-01-11 12:48 UTC
